version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports: ["2181:2181"]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - uab-net
  kafka:
    image: confluentinc/cp-kafka
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - uab-net
  redis:
    image: redis
    ports: ["6379:6379"]
  mongodb:
    image: mongo
    ports: ["27017:27017"]
  cassandra:
    image: cassandra
    ports: ["9042:9042"]
networks:
  uab-net:
    driver: bridge